#!/bin/sh

grep -q "bacnetclient call _cron" /etc/crontabs/root || echo "* * *  *  * /usr/libexec/rpcd/bacnetclient call _cron" >> /etc/crontabs/root
grep -q "rsync -a --delete /tmp/rrd /etc/luci-uploads/" /etc/crontabs/root || echo "21 */1 *  *  * rsync -a --delete /tmp/rrd /etc/luci-uploads/" >> /etc/crontabs/root
uci set luci_statistics.collectd_unixsock.enable='1'
uci commit luci_statistics

if ! grep -q "rsync -a /etc/luci-uploads/rrd /tmp/" /etc/rc.local ; then
	echo "rsync -a /etc/luci-uploads/rrd /tmp/" > /tmp/rc.local
	cat /etc/rc.local >> /tmp/rc.local
	mv /tmp/rc.local /etc/rc.local
fi
