#!/bin/sh

#PATH=$PATH:"/Users/patrick/bacnet-stack-test/bin"
#export BACNET_IFACE=eth0
#*/10 * *  *  * bacwi -1 > /tmp/address_cache

[ -f /lib/functions.sh ] && . /lib/functions.sh
[ -f /usr/share/libubox/jshn.sh ] && . /usr/share/libubox/jshn.sh
[ -f /usr/local/share/libubox/jshn.sh ] && . /usr/local/share/libubox/jshn.sh
[ -f /lib/functions/network.sh ] && . /lib/functions/network.sh

set -o pipefail

cd /tmp

log() {
	if [ "$BACNET_DEBUG" == "1" ] ; then
		logger -t bacnetclient "$@"
	fi
}

get_event() {
	local data=$1
	OOIFS=$IFS
	IFS=$OIFS
	set $data
	local id="$1"
	local object_type="$2"
	local object_instance="$3"
	json_add_string "object_instance" "$object_instance"
	json_add_string "object_type" "$object_type"
	object_name="$(bacrp $id $object_type $object_instance object-name | tr -d '\r')"
	[ "$?" == "0" ] || object_name="Type$object_type""Instance$instance"
	json_add_string "object_name" "$object_name"
	Description="$(bacrp $id $object_type $object_instance Description | tr -d '\r')"
	[ "$?" == "0" ] || Description="$object_name"
	json_add_string "Description" "$Description"
	event_state="$(bacrp $id $object_type $object_instance event-state | tr -d '\r')"
	[ "$?" == "0" ] || event_state="invalid"

	event_time_stamp_normal="0"
	event_state_u="$event_state"
	case $event_state in
		"low limit")
			event_state="Grenzwertunterschreitung"
			event_state_u="low_limit"
		;;
		"high limit")
			event_state="Grenzwertüberschreitung"
			event_state_u="high_limit"
		;;
		"normal")
			event_state="Normal"
			event_time_stamp_normal="$(bacrp $id $object_type $object_instance event-time-stamps 3 | tr -d '\r')"
			[ "$?" == "0" ] || event_time_stamp_normal="0"
		;;
		"fault")
			event_state="Fehler"
		;;
		"offnormal")
			event_state="Störung"
		;;
	esac
	json_add_string "event_state" "$event_state"
	json_add_string "event_time_stamp_normal" "$event_time_stamp_normal"

	event_time_stamp="$(bacrp $id $object_type $object_instance event-time-stamps 1 | tr -d '\r')"
	if [ "$?" != "0" ] ; then
		event_time_stamp="$(bacrp $id $object_type $object_instance event-time-stamps -1 | tr -d '\r'| tr -d '{}' | cut -d ',' -f 1)"
		if [ "$?" != "0" ] ; then
			event_time_stamp=0
		fi
	fi
	json_add_string "event_time_stamp" "$event_time_stamp"

	value="$(bacrp $id $object_type $object_instance present-value 2>/dev/null | tr -d '\r')"
	[ "$?" == "0" ] || value="invalid"
	unit=""
	low_limit=""
	high_limit=""
	case $value in
		active*)
			value="$(bacrp $id $object_type $object_instance active-text | tr -d '\r')"
			[ "$?" == "0" ] || value="active"
			json_add_string "value" "$value"
		;;
		inactive*)
			value="$(bacrp $id $object_type $object_instance inactive-text | tr -d '\r')"
			[ "$?" == "0" ] || value="inactive"
			json_add_string "value" "$value"
		;;
		*[0-9])
			json_add_string "value" "$value"
			units="$(bacrp $id $object_type $object_instance units | tr -d '\r')"
			[ "$?" == "0" ] || units=""
			json_add_string "units" "$units"
			low_limit="$(bacrp $id $object_type $object_instance low-limit | tr -d '\r')"
			[ "$?" == "0" ] || low_limit=""
			json_add_string "low_limit" "$low_limit"
			high_limit="$(bacrp $id $object_type $object_instance high-limit | tr -d '\r')"
			[ "$?" == "0" ] || high_limit=""
			json_add_string "high_limit" "$high_limit"
		;;
		*)
			json_add_string "value" "0"
		;;
	esac
	IFS=$OOIFS
	if [ "$BACNET_MAIL" == "1" ] ; then
		log "msmtp $dev $id $object_type $object_instance $event_state"
		if [ ! -f /tmp/bacevent/$id-$object_type-$object_instance-$event_state_u ] ; then
			log "msmtp $id $object_type $object_instance $event_state"
			echo "To: $BACNET_MAIL_TO" > /tmp/mail.txt
			echo "Cc: $BACNET_MAIL_CC" >> /tmp/mail.txt
			echo "Bcc: $BACNET_MAIL_BCC" >> /tmp/mail.txt
			#echo "Subject: Event $object_name" >> /tmp/mail.txt
			#echo "Event $object_name $Description $value $unit $low_limit $unit - $high_limit $unit $event_state" >> /tmp/mail.txt
			cat /etc/bacalarmtemplate.txt | sed -e "s/#event_state#/$event_state/"\
			 -e "s/#dev#/$dev/"  -e "s/#object_name#/$object_name/"  -e "s/#Description#/$Description/" \
			 -e "s/#value#/$value $unit   $low_limit $unit - $high_limit $unit/"  -e "s/#devdesc#/$devdesc/"  -e "s/#devloc#/$devloc/" \
			 -e "s/#event_time_stamp#/$event_time_stamp/" >> /tmp/mail.txt
			echo "$BACNET_MAIL_PW" > /tmp/mail_pw.txt
			ping -4 -c 1 $BACNET_MAIL_SERVER >/dev/null 2>/dev/null
			/usr/bin/msmtp --host="$BACNET_MAIL_SERVER" --port="$BACNET_MAIL_PORT" --tls="on" --auth="plain" --user="$BACNET_MAIL_USER" --password="cat /tmp/mail_pw.txt" --from="$BACNET_MAIL_FROM" --read-recipients --syslog="on" -- "$BACNET_MAIL_TO" < /tmp/mail.txt >/dev/null 2&>1
		fi
		log "msmtp touch /tmp/bacevent_tmp/$id-$object_type-$object_instance-$event_state_u"
		touch /tmp/bacevent_tmp/$id-$object_type-$object_instance-$event_state_u
	fi
}

get_eventlist() {
	local id="$1"
	local dev=""
	support="$(bacrp $id device $id protocol-services-supported | cut -d ',' -f4)"
	[ "$?" == "0" ] || return
	[ "$support" == "true" ] || return
	log "get_eventlist $id"
	dev="$(bacrp $id device $id object-name | tr -d '\r')"
	[ "$?" == "0" ] || return
	devdesc="$(bacrp $id device $id Description | tr -d '\r')"
	[ "$?" == "0" ] || return
	devloc="$(bacrp $id device $id Location | tr -d '\r')"
	[ "$?" == "0" ] || return
	OIFS=$IFS
	IFS=$'\n'
	for line in $(bacge $id|grep $id);do
		idx=$((idx+1))
		json_add_object 0
		json_add_string "idx" "$idx"
		json_add_string "devid" "$id"
		json_add_string "devname" "$dev"
		json_add_string "devdesc" "$devdesc"
		json_add_string "devloc" "$devloc"
		get_event "$line"
		json_close_object
	done
	IFS=$OIFS
	if [ "$BACNET_MAIL" == "1" ] ; then
		rm -f /tmp/bacevent/$id-*
		mv /tmp/bacevent_tmp/$id-* /tmp/bacevent/
	fi
}

get_eventlistjson() {
	local id="$1"
	local dev=""
	[ -f /tmp/bacnetclient.lock ] && return
	touch /tmp/bacnetclient.lock
	log "get_eventlistjson $id"
	support="$(bacrp $id device $id protocol-services-supported | cut -d ',' -f4)"
	[ "$?" == "0" ] || return
	[ "$support" == "true" ] || return
	dev="$(bacrp $id device $id object-name | tr -d '\r')"
	[ "$?" == "0" ] || return
	devdesc="$(bacrp $id device $id Description | tr -d '\r')"
	[ "$?" == "0" ] || return
	devloc="$(bacrp $id device $id Location | tr -d '\r')"
	[ "$?" == "0" ] || return
	json_init
	json_add_array "list"
	OIFS=$IFS
	IFS=$'\n'
	for line in $(bacge $id|grep $id);do
		idx=$((idx+1))
		json_add_object 0
		json_add_string "idx" "$idx"
		json_add_string "devid" "$id"
		json_add_string "devname" "$dev"
		json_add_string "devdesc" "$devdesc"
		json_add_string "devloc" "$devloc"
		get_event "$line"
		json_close_object
	done
	IFS=$OIFS
	json_close_array
	json_dump > /tmp/eventlist_$id.json.tmp
	json_cleanup
	mv /tmp/eventlist_$id.json.tmp /tmp/eventlist_$id.json
	rm /tmp/bacnetclient.lock
}

get_devlist() {
	local id="$1"
	local dev=""
	log "get_devlist $id"
	dev="$(bacrp $id device $id object-name | tr -d '\r')"
	[ "$?" == "0" ] || return
	devdesc="$(bacrp $id device $id Description | tr -d '\r')"
	[ "$?" == "0" ] || return
	devloc="$(bacrp $id device $id Location | tr -d '\r')"
	[ "$?" == "0" ] || return
	json_add_object 0
	json_add_string "devid" "$id"
	json_add_string "object_name" "$dev"
	json_add_string "Description" "$devdesc"
	json_add_string "Location" "$devloc"
	json_close_object
}

get_objlist() {
	local id="$1"
	[ -f /tmp/objlist_$id.json.get ] || return
	[ -f /tmp/bacnetclient.lock ] && return
	touch /tmp/bacnetclient.lock
	bacrp $id device $id object-list > /tmp/obj$id.json.tmp
	status=$?
	if [ "$status" == "0" ]; then
		cat /tmp/obj$id.json.tmp | tr -d '\r' | sed -e 's/{/{"list": [/' -e 's/}/]}/' -e 's/(\([a-z-]*\), \([0-9]*\))/{"\1": \2}/g' > /tmp/obj$id.json
		rm -f /tmp/obj$id.json.tmp
	else
		#TODO Segmentation Not Supported
		i=1
		bacrp $id device $id object-list $i > /tmp/obj$id.json.tmp
		status=$?
		echo '{"list": [' > /tmp/obj$id.json
		if [ "$status" == "0" ]; then
			cat /tmp/obj$id.json.tmp | tr -d '\r' | sed -e 's/(\([a-z-]*\), \([0-9]*\))/{"\1": \2}/g' >> /tmp/obj$id.json
		fi
		rm -f /tmp/obj$id.json.tmp
		while [ "$status" == "0" ] ; do
			i=$(( i + 1 ))
			bacrp $id device $id object-list $i > /tmp/obj$id.json.tmp
			status=$?
			if [ "$status" == "0" ]; then
				echo "," >> /tmp/obj$id.json
				cat /tmp/obj$id.json.tmp | tr -d '\r' | sed -e 's/(\([a-z-]*\), \([0-9]*\))/{"\1": \2}/g' >> /tmp/obj$id.json
			fi
			rm -f /tmp/obj$id.json.tmp
		done
		echo "" >> /tmp/obj$id.json
		echo ']}' >> /tmp/obj$id.json
	fi
	json_init
	json_load_file /tmp/obj$id.json
	#rm /tmp/obj$id.json
	json_select "list"
	i=1;while json_is_a ${i} object;do
		json_select $i
		json_get_keys object_type
		object_type="$(echo $object_type | tr _ -)"
		json_get_var object_instance $object_type
		object_name="$(bacrp $id $object_type $object_instance object-name | tr -d '\r')"
		[ "$?" == "0" ] || object_name=""
		Description="$(bacrp $id $object_type $object_instance Description | tr -d '\r')"
		[ "$?" == "0" ] || Description=""
		json_add_string "devid" "$id"
		json_add_string "object_type" "$object_type"
		json_add_string "object_instance" "$object_instance"
		json_add_string "object_name" "$object_name"
		json_add_string "Description" "$Description"
		json_select ..
		i=$(( i + 1 ))
	done
	json_dump > /tmp/objlist_$id.json.tmp
	json_cleanup
	mv /tmp/objlist_$id.json.tmp /tmp/objlist_$id.json
	rm -f /tmp/objlist_$id.json.get
	rm /tmp/bacnetclient.lock
}

eventlist() {
	[ -f /tmp/bacnetclient.lock ] && return
	touch /tmp/bacnetclient.lock
	[ -f /tmp/devlist.json ] || ( touch /tmp/devlist.json.get ; return )
	local devids=""
	json_init
	json_load_file /tmp/devlist.json
	json_select "list"
	dev_idx=1;while json_is_a ${dev_idx} object;do
		json_select ${dev_idx}
		json_get_var devid devid
		devids="$devids $devid"
		json_select ..
		dev_idx=$(( dev_idx + 1 ))
	done
	json_cleanup
	local idx=0
	log "eventlist dev $devids"
	json_init
	json_add_array "list"
	for devid in $devids; do
		get_eventlist "$devid"
	done
	json_close_array
	json_dump > /tmp/eventlist.json.tmp
	json_cleanup
	mv /tmp/eventlist.json.tmp /tmp/eventlist.json
	rm /tmp/bacnetclient.lock
}

eventlistjson() {
	[ -f /tmp/bacnetclient.lock ] && return
	touch /tmp/bacnetclient.lock
	local idx=0
	log "eventlistjson"
	[ -f /tmp/devlist.json ] || return
	local devids=""
	json_init
	json_load_file /tmp/devlist.json
	json_select "list"
	i=1;while json_is_a ${i} object;do
		if [ -f /tmp/objlist_$i.json.get ] ; then
			json_select ${i}
			json_get_var devid devid
			devids="$devids $devid"
			json_select ..
		fi
	done
	json_cleanup
	for devid in $devids; do
		get_eventlistjson "$devid"
	done
	rm /tmp/bacnetclient.lock
}

devlist() {
	[ -f /tmp/bacnetclient.lock ] && return
	touch /tmp/bacnetclient.lock
	log "devlist"
	devids="$(bacwi | tr -d '\r' | grep -v ';' | cut -d ' ' -f 3)"
	if [ "$?" == "0" ] ; then
		json_init
		json_add_array "list"
		for devid in $devids;do
			deny=0
			for deny_id in $BACNET_DENY_LIST ; do
				if [ "$devid" == "$deny_id" ] ; then
					deny=1
				fi
			done
			if [ "$deny" == "0" ] ; then
				get_devlist "$devid"
			fi
		done
		json_close_array
		json_dump > /tmp/devlist.json.tmp
		json_cleanup
		mv /tmp/devlist.json.tmp /tmp/devlist.json
	fi
	rm /tmp/bacnetclient.lock
}

objlist() {
	read data
	json_load "$data"
	json_get_var devid devid
	json_cleanup
	touch /tmp/objlist_$devid.json.get
	[ -f /tmp/objlist_$devid.json ] && cat /tmp/objlist_$devid.json || \
	echo '{"list": [ { "devid": "'$devid'","object_type": "wait", "object_instance": "'$(date +%M%S)'"} ] }'
}

deveventlist() {
	read data
	json_load "$data"
	json_get_var devid devid
	json_cleanup
	touch /tmp/eventlist_$devid.json.get
	[ -f /tmp/eventlist_$devid.json ] && cat /tmp/eventlist_$devid.json || \
	echo '{"list": [ { "devid": "'$devid'","object_name": "wait", "Description": "'$(date +%M%S)'"} ] }'
}

objlistjson() {
	[ -f /tmp/devlist.json ] || ( touch /tmp/devlist.json.get ; return )
	local devids=""
	json_init
	json_load_file /tmp/devlist.json
	json_select "list"
	dev_idx=1;while json_is_a ${dev_idx} object;do
		json_select ${dev_idx}
		json_get_var devid devid
		if [ -f /tmp/objlist_$devid.json.get ] ; then
			devids="$devid $devids"
		fi
		json_select ..
		dev_idx=$(( dev_idx + 1 ))
	done
	json_cleanup
	log "objlistjson dev $devids"
	for devid in $devids; do
		get_objlist "$devid"
	done
}

write_objdesc() {
	read data
	json_load "$data"
	json_get_var devid devid
	json_get_var object_type object_type
	json_get_var object_instance object_instance
	json_get_var Description Description
	json_cleanup
	object_type="$(echo $object_type | tr _ -)"
	log "write $devid $object_type $object_instance $Description"
	bacwp "$devid" "$object_type" "$object_instance" "Description" "16" "-1" "7" "$Description"
}

write_objloc() {
	read data
	json_load "$data"
	json_get_var devid devid
	json_get_var object_type object_type
	json_get_var object_instance object_instance
	json_get_var Location Location
	json_cleanup
	object_type="$(echo $object_type | tr _ -)"
	log "write $devid $object_type $object_instance $Location"
	bacwp "$devid" "$object_type" "$object_instance" "Location" "16" "-1" "7" "$Location"
}

write_ackalarm() {
	read data
	json_load "$data"
	json_get_var devid devid
	json_get_var object_type object_type
	json_get_var object_instance object_instance
	json_get_var event_time_stamp event_time_stamp
	json_get_var state state
	process_id=10
	ack_date="$(date +%Y/%m/%d-%H:%M:%S)"
	event_time_stamp=$(($event_time_stamp/1000))
	event_date="$(date -d @$event_time_stamp "+%Y/%m/%d-%H:%M:%S")"
	log "bacackalarm $devid $process_id $object_type $object_instance $state $event_date openwrt $ack_date"
	bacackalarm "$devid" "$process_id" "$object_type" "$object_instance" "$state" "$event_date" "openwrt" "$ack_date"
}

get_config() {
	config_load bacnetclient
	config_get iface default iface "br-lan"
	[ -z "$iface" ] || export BACNET_IFACE="$iface"
	config_get port default port
	#set random src port with bbmd
	#rand="$(echo -n $(head -n 1 /dev/urandom 2>/dev/null | md5sum | cut -b 1-5))"
	#port="$(printf "%d" "0x$rand")"
	[ -z "$port" ] || export BACNET_IP_PORT="$port"
	config_get bbmd_addr default bbmd_addr
	[ -z "$bbmd_addr" ] || export BACNET_BBMD_ADDRESS="$bbmd_addr"
	config_get bbmd_port default bbmd_port
	[ -z "$bbmd_port" ] || export BACNET_BBMD_PORT="$bbmd_port"
	export BACNET_DENY_LIST=""
	config_get deny_list default deny_list
	[ -z "$deny_list" ] || export BACNET_DENY_LIST="$deny_list"
	export BACNET_DEBUG="0"
	config_get debug default debug
	[ -z "$debug" ] || export BACNET_DEBUG="$debug"
	if [ -f /usr/bin/msmtp ] ; then
		config_get mail default mail
		[ -z "$mail" ] || export BACNET_MAIL="$mail"
		if [ "$BACNET_MAIL" == "1" ] ; then
			config_get mail_from default mail_from
			[ -z "$mail_from" ] || export BACNET_MAIL_FROM="$mail_from"
			config_get mail_to default mail_to
			[ -z "$mail_to" ] || export BACNET_MAIL_TO="$mail_to"
			config_get mail_cc default mail_cc
			[ -z "$mail_cc" ] || export BACNET_MAIL_CC="$mail_cc"
			config_get mail_bc default mail_bcc
			[ -z "$mail_bcc" ] || export BACNET_MAIL_BCC="$mail_bcC"
			config_get mail_server default mail_server
			[ -z "$mail_server" ] || export BACNET_MAIL_SERVER="$mail_server"
			config_get mail_port default mail_port
			[ -z "$mail_port" ] || export BACNET_MAIL_PORT="$mail_port"
			config_get mail_user default mail_user
			[ -z "$mail_user" ] || export BACNET_MAIL_USER="$mail_user"
			config_get mail_pw default mail_pw
			[ -z "$mail_pw" ] || export BACNET_MAIL_PW="$mail_pw"
			mkdir -p /tmp/bacevent
			mkdir -p /tmp/bacevent_tmp
		fi
	fi
	log "$BACNET_IFACE $BACNET_IP_PORT $BACNET_BBMD_ADDRESS $BACNET_BBMD_PORT"
}

case "$1" in
	list)
		json_init
		json_add_object "eventlist"
		json_close_object
		json_add_object "deveventlist"
		json_add_string "devid" "devid"
		json_close_object
		json_add_object "devlist"
		json_close_object
		json_add_object "objlist"
		json_add_string "devid" "devid"
		json_close_object
		json_add_object "objdesc"
		json_add_string "devid" "devid"
		json_add_string "object_instance" "object_instance"
		json_add_string "Description" "Description"
		json_close_object
		json_add_object "objloc"
		json_add_string "devid" "devid"
		json_add_string "object_instance" "object_instance"
		json_add_string "Location" "Location"
		json_close_object
		json_add_object "ackevent"
		json_add_string "devid" "devid"
		json_add_string "object_instance" "object_instance"
		json_add_string "event_time_stamp" "event_time_stamp"
		json_close_object
		json_dump
	;;
	call)
		case "$2" in
			eventlist) 
				cat /tmp/eventlist.json || \
				echo '{"list": [ { "idx": "0","devid": "'$(date +%M%S)'", "devname": "wait"} ] }'
				touch /tmp/eventlist.json.get
			;;
			devlist) 
				cat /tmp/devlist.json || \
				echo '{"list": [ { "devid": "'$(date +%M%S)'","object_name": "wait"} ] }'
				touch /tmp/devlist.json.get
			;;
			objlist)
				objlist
				touch /tmp/objlist.json.get
			;;
			deveventlist)
				deveventlist
				touch /tmp/deveventlist.json.get
			;;
			objdesc) get_config && write_objdesc ;;
			objloc) get_config && write_objloc ;;
			ackevent) get_config && write_ackalarm ;;
			_cron)
				[ -f /tmp/devlist.json.get ] && get_config && devlist
				rm -f /tmp/devlist.json.get
				[ -f /tmp/eventlist.json.get ] && get_config && eventlist
				rm -f /tmp/eventlist.json.get
				[ -f /tmp/objlist.json.get ] && get_config && objlistjson
				rm -f /tmp/objlist.json.get
				[ -f /tmp/deveventlist.json.get ] && get_config && eventlistjson
				rm -f /tmp/deveventlist.json.get
			;;
		esac
	;;
esac
